name: Update THM Badge

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Screenshot THM Badge
        uses: JonathanTreffler/screenshot-action@v1.0
        with:
          url: https://tryhackme.com/api/v2/badges/public-profile?userPublicId=5230186
          width: 330
          height: 90
          # Espera 5 segundos para carregar o widget e as fontes
          wait_for: 5000 
          output: assets/thm-dynamic-badge.png

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/thm-dynamic-badge.png
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update THM Badge" && git push)