name: Update THM Badge
 
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest # Pode manter o 24.04, o shot-scraper lida bem
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install shot-scraper
        run: |
          pip install shot-scraper
          shot-scraper install

      - name: Create assets directory
        run: mkdir -p assets

      - name: Screenshot THM Badge
        run: |
          shot-scraper https://tryhackme.com/api/v2/badges/public-profile?userPublicId=5230186 \
          -o assets/thm-dynamic-badge.png \
          --selector "#thm-badge" \
          --padding 0 \
          --wait 5000

      - name: Verify file existence
        run: ls -lh assets/thm-dynamic-badge.png

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/thm-dynamic-badge.png
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update THM Dynamic Badge" && git push)